### ISSUE TITLE
Switch to one excecutable

### ISSUE THREAD

**Issue by calebeby** [jstransformers/nuke#10]
Hi guys,

Should we switch to having an `index.js` which uses [commander.js](https://github.com/tj/commander.js) and git-style subcommands?

This way, we can...

```bash
$ npm install nuke # or another name
```

```bash
$ nuke clone
```

etc.

Interested?

**Comment by RobLoach** [comment]
yez

**Comment by TimothyGu** [comment]
Fixed in #11
